# Generated by Django 5.2.17 on 2026-09-19 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('dismissed', 'Уволен')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaxAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_user_id', models.BigIntegerField(unique=True)),
                ('dialog_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(blank=True, choices=[('owner', 'Владелец'), ('employee', 'Сотрудник')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='core.maxaccount'),
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network', to='core.maxaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='core.network')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.store'),
        ),
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Запланирована'), ('reminded', 'Напоминание отправлено'), ('awaiting_photo', 'Ожидает фото'), ('done_on_time', 'Выполнена вовремя'), ('done_late', 'Выполнена с опозданием'), ('overdue', 'Просрочена'), ('unclaimed', 'Никто не взял'), ('missed', 'Не выполнена за смену')], default='scheduled', max_length=16)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('overdue_notified_at', models.DateTimeField(blank=True, null=True)),
                ('closing_notified_at', models.DateTimeField(blank=True, null=True)),
                ('awaiting_photo_since', models.DateTimeField(blank=True, null=True)),
                ('awaiting_photo_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.employee')),
            ],
            options={
                'ordering': ['date', 'template__planned_time'],
            },
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField()),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('photo', models.FileField(blank=True, upload_to='completions/%Y/%m/%d/')),
                ('photo_token', models.CharField(blank=True, max_length=512)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completions', to='core.employee')),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='core.taskinstance')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='core.employee')),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='core.taskinstance')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('daily', 'Ежедневная'), ('one_time', 'Разовая на дату')], default='daily', max_length=16)),
                ('planned_time', models.TimeField()),
                ('on_date', models.DateField(blank=True, null=True)),
                ('tolerance_minutes', models.PositiveSmallIntegerField(default=15)),
                ('requires_photo', models.BooleanField(default=True)),
                ('requires_claim', models.BooleanField(default=False)),
                ('photo_prompt', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='core.store')),
            ],
            options={
                'ordering': ['planned_time'],
            },
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='core.tasktemplate'),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликована')], default='draft', max_length=16)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='core.employee')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='core.store')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['store', 'date'], name='core_shift_store_i_64eb90_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='shift_end_after_start')],
            },
        ),
        migrations.AddConstraint(
            model_name='tasktemplate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'daily'), ('on_date__isnull', True)), models.Q(('kind', 'one_time'), ('on_date__isnull', False)), _connector='OR'), name='task_template_date_matches_kind'),
        ),
        migrations.AddConstraint(
            model_name='taskinstance',
            constraint=models.UniqueConstraint(fields=('template', 'date'), name='uniq_task_instance_per_day'),
        ),
    ]
