# Generated by Django 5.2.17 on 2026-09-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tasktemplate_available_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('dismissed', 'Уволен'), ('removed', 'Убран из списка')], default='active', max_length=16),
        ),
    ]
